-- Raw leads import from Outscraper CSV
-- This table stores the raw data for analysis before processing

CREATE TABLE IF NOT EXISTS leads_raw (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  query TEXT,
  name TEXT,
  name_for_emails TEXT,
  site TEXT,
  subtypes TEXT,
  category TEXT,
  type_value TEXT,
  phone TEXT,
  phone_phones_enricher_carrier_type TEXT,
  phone_phones_enricher_carrier_name TEXT,
  phone_phones_enricher_avoid_saving TEXT,
  full_address TEXT,
  borough TEXT,
  street TEXT,
  city TEXT,
  postal_code TEXT,
  state TEXT,
  us_state TEXT,
  country TEXT,
  country_code TEXT,
  latitude TEXT,
  longitude TEXT,
  h3 TEXT,
  time_zone TEXT,
  plus_code TEXT,
  area_service TEXT,
  rating TEXT,
  reviews TEXT,
  reviews_link TEXT,
  reviews_tags TEXT,
  reviews_per_score TEXT,
  reviews_per_score_1 TEXT,
  reviews_per_score_2 TEXT,
  reviews_per_score_3 TEXT,
  reviews_per_score_4 TEXT,
  reviews_per_score_5 TEXT,
  photos_count TEXT,
  photo TEXT,
  street_view TEXT,
  located_in TEXT,
  working_hours TEXT,
  working_hours_csv_compatible TEXT,
  working_hours_old_format TEXT,
  other_hours TEXT,
  popular_times TEXT,
  business_status TEXT,
  about TEXT,
  range_value TEXT,
  prices TEXT,
  posts TEXT,
  logo TEXT,
  description TEXT,
  typical_time_spent TEXT,
  verified TEXT,
  owner_id TEXT,
  owner_title TEXT,
  owner_link TEXT,
  reservation_links TEXT,
  booking_appointment_link TEXT,
  menu_link TEXT,
  order_links TEXT,
  location_link TEXT,
  location_reviews_link TEXT,
  place_id TEXT,
  google_id TEXT,
  cid TEXT,
  kgmid TEXT,
  reviews_id TEXT,
  located_google_id TEXT,
  email_1 TEXT,
  email_1_emails_validator_status TEXT,
  email_1_emails_validator_status_details TEXT,
  email_1_full_name TEXT,
  email_1_first_name TEXT,
  email_1_last_name TEXT,
  email_1_title TEXT,
  email_1_phone TEXT,
  email_2 TEXT,
  email_2_emails_validator_status TEXT,
  email_2_emails_validator_status_details TEXT,
  email_2_full_name TEXT,
  email_2_first_name TEXT,
  email_2_last_name TEXT,
  email_2_title TEXT,
  email_2_phone TEXT,
  email_3 TEXT,
  email_3_emails_validator_status TEXT,
  email_3_emails_validator_status_details TEXT,
  email_3_full_name TEXT,
  email_3_first_name TEXT,
  email_3_last_name TEXT,
  email_3_title TEXT,
  email_3_phone TEXT,
  phone_1 TEXT,
  phone_1_phones_enricher_carrier_name TEXT,
  phone_1_phones_enricher_carrier_type TEXT,
  phone_1_phones_enricher_avoid_saving TEXT,
  phone_2 TEXT,
  phone_2_phones_enricher_carrier_name TEXT,
  phone_2_phones_enricher_carrier_type TEXT,
  phone_2_phones_enricher_avoid_saving TEXT,
  phone_3 TEXT,
  phone_3_phones_enricher_carrier_type TEXT,
  phone_3_phones_enricher_carrier_name TEXT,
  phone_3_phones_enricher_avoid_saving TEXT,
  facebook TEXT,
  instagram TEXT,
  linkedin TEXT,
  tiktok TEXT,
  medium TEXT,
  reddit TEXT,
  skype TEXT,
  snapchat TEXT,
  telegram TEXT,
  whatsapp TEXT,
  twitter TEXT,
  vimeo TEXT,
  youtube TEXT,
  github TEXT,
  crunchbase TEXT,
  website_title TEXT,
  website_generator TEXT,
  website_description TEXT,
  website_keywords TEXT,
  website_has_fb_pixel TEXT,
  website_has_google_tag TEXT
);

-- Indexes on important fields for filtering/searching
CREATE INDEX idx_leads_raw_name ON leads_raw(name);
CREATE INDEX idx_leads_raw_state ON leads_raw(state);
CREATE INDEX idx_leads_raw_city ON leads_raw(city);
CREATE INDEX idx_leads_raw_place_id ON leads_raw(place_id);
CREATE INDEX idx_leads_raw_rating ON leads_raw(rating);
CREATE INDEX idx_leads_raw_category ON leads_raw(category);

-- Enable RLS (admin only access for now)
ALTER TABLE leads_raw ENABLE ROW LEVEL SECURITY;

-- Only admins can access leads_raw
CREATE POLICY "Admin access to leads_raw" ON leads_raw
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM contractors
      WHERE contractors.id = auth.uid()
      AND contractors.is_admin = true
    )
  );
